#!/usr/bin/env php
<?php

// Load Composer's autoloader
require_once __DIR__ . "/vendor/autoload.php";

// Initiate Bootstrap
$BOOTSTRAP = new LaswitchTech\Core\Bootstrap("CLI");

// Import the debugger
require_once 'webroot/debug.php';
