<?php
// Core-Web — Project Root Entry Point
// Generated by: php cli core init
// This file serves as the entry point for shared hosting environments
// where the document root cannot be configured.
// For advanced setups, point the document root to webroot/ and use webroot/index.php instead.

// Load Composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// Load environment if .env exists
if (file_exists(__DIR__ . '/.env')) {
    $lines = file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        if (strpos($line, '=') !== false) {
            [$key, $value] = explode('=', $line, 2);
            $_ENV[trim($key)] = trim($value);
        }
    }
}

// Bootstrap Core-Web
$BOOTSTRAP = new \LaswitchTech\Core\Bootstrap('ROUTER');
